# GitHub Sponsors funding options for AI Team Orchestrator

github: # GitHub username for sponsorship
ko_fi: # Ko-fi username
patreon: # Patreon username
open_collective: # Open Collective slug
custom: ["https://books.danielepelleri.com", "https://your-website.com/sponsor"]